version: "3"
services:
  wp:
    image: wordpress
    ports:
      - 8080:80               # host_port:container_port
    environment:
      # WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass@word01
      WORDPRESS_DB_NAME: wordpress   
    # links:
    #   - mysql:database      # service:alias
    depends_on:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: pass@word01
    ports:
      - 3306:3306